openapi: 3.0.0
info:
  title: Auth App
  version: 1.0.0
  description: Auth App Services.
  contact:
    email: ravisharmacs09@gmail.com
  license:
    name: Private

paths:
  /auth/signup:
    post:
      summary: Sign up with your username, email and password
      description: Endpoint to register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: User creation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /auth/signin:
    post:
      summary: Sign in with email and password
      description: Endpoint to authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Authentication Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refreshToken:
                    type: string
                  userInfo:
                    type: object
                    properties:
                      userId: 
                        type: string
                      userName: 
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
        '400':
          description: Authentication Failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /auth/users:
    get:
      summary: Fetch all users
      description: Endpoint to fetch all users
      responses:
        '200':
          description: Users fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                    username:
                      type: string
                    email:
                      type: string
                    address:
                      type: object
                      properties:
                        street:
                          type: string
                        suite:
                          type: string
                        city:
                          type: string
                        zipcode:
                          type: string
                        geo:
                          type: object
                          properties:
                            lat:
                              type: string
                            lng:
                              type: string
                    phone:
                      type: string
                    website:
                      type: string
                    company:
                      type: object
                      properties:
                        name:
                          type: string
                        catchPhrase:
                          type: string
                        bs:
                          type: string
              example:
                - id: 1
                  name: "Leanne Graham"
                  username: "Bret"
                  email: "Sincere@april.biz"
                  address:
                    street: "Kulas Light"
                    suite: "Apt. 556"
                    city: "Gwenborough"
                    zipcode: "92998-3874"
                    geo:
                      lat: "-37.3159"
                      lng: "81.1496"
                  phone: "1-770-736-8031 x56442"
                  website: "hildegard.org"
                  company:
                    name: "Romaguera-Crona"
                    catchPhrase: "Multi-layered client-server neural-net"
                    bs: "harness real-time e-markets"