openapi: 3.0.0
info:
  title: Auth App
  version: 1.0.0
  description: Auth App Services.
  contact:
    email: ravisharmacs09@gmail.com
  license:
    name: Private

paths:
  /auth/signup:
    post:
      summary: Sign up with your username, email and password
      description: Endpoint to register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: User creation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /auth/signin:
    post:
      summary: Sign in with email and password
      description: Endpoint to authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Authentication Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refreshToken:
                    type: string
                  userInfo:
                    type: object
                    properties:
                      userId: 
                        type: string
                      userName: 
                        type: string
                      firstName:
                        type: string
                      lastName:
                        type: string
        '400':
          description: Authentication Failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string